const fs = require('fs');
const path = require('path');

const fileP = path.join(__dirname, '../src/data/nse-stocks.ts');
const existingContent = fs.readFileSync(fileP, 'utf8');

const existingSymbols = new Set();
const regex = /symbol:\s*"([^"]+)"/g;
let match;
while ((match = regex.exec(existingContent)) !== null) {
  existingSymbols.add(match[1]);
}

const allStocks = [
  { symbol: 'ADANIENT.NS', name: 'Adani Enterprises', sector: 'Miscellaneous' },
  { symbol: 'ADANIGREEN.NS', name: 'Adani Green Energy', sector: 'Energy' },
  { symbol: 'APOLLOHOSP.NS', name: 'Apollo Hospitals', sector: 'Healthcare' },
  { symbol: 'BAJAJFINSV.NS', name: 'Bajaj Finserv', sector: 'Financial Services' },
  { symbol: 'BAJAJHLDNG.NS', name: 'Bajaj Holdings', sector: 'Financial Services' },
  { symbol: 'BANDHANBNK.NS', name: 'Bandhan Bank', sector: 'Banking' },
  { symbol: 'BERGEPAINT.NS', name: 'Berger Paints', sector: 'Consumer' },
  { symbol: 'CHOLAFIN.NS', name: 'Cholamandalam Investment', sector: 'Financial Services' },
  { symbol: 'COALINDIA.NS', name: 'Coal India', sector: 'Energy' },
  { symbol: 'DLF.NS', name: 'DLF', sector: 'Real Estate' },
  { symbol: 'EICHERMOT.NS', name: 'Eicher Motors', sector: 'Auto' },
  { symbol: 'GAIL.NS', name: 'GAIL India', sector: 'Energy' },
  { symbol: 'GODREJPROP.NS', name: 'Godrej Properties', sector: 'Real Estate' },
  { symbol: 'GRASIM.NS', name: 'Grasim Industries', sector: 'Infrastructure' },
  { symbol: 'HAL.NS', name: 'Hindustan Aeronautics', sector: 'Defense' },
  { symbol: 'HDFCAMC.NS', name: 'HDFC Asset Management', sector: 'Financial Services' },
  { symbol: 'ICICIGI.NS', name: 'ICICI Lombard', sector: 'Financial Services' },
  { symbol: 'ICICIPRULI.NS', name: 'ICICI Prudential Life', sector: 'Financial Services' },
  { symbol: 'IGL.NS', name: 'Indraprastha Gas', sector: 'Energy' },
  { symbol: 'INDIGO.NS', name: 'InterGlobe Aviation', sector: 'Aviation' },
  { symbol: 'IOC.NS', name: 'Indian Oil Corporation', sector: 'Energy' },
  { symbol: 'IRCTC.NS', name: 'IRCTC', sector: 'Services' },
  { symbol: 'LTIM.NS', name: 'LTIMindtree', sector: 'IT' },
  { symbol: 'MUTHOOTFIN.NS', name: 'Muthoot Finance', sector: 'Financial Services' },
  { symbol: 'NAUKRI.NS', name: 'Info Edge', sector: 'IT' },
  { symbol: 'PEL.NS', name: 'Piramal Enterprises', sector: 'Financial Services' },
  { symbol: 'PIIND.NS', name: 'PI Industries', sector: 'Chemicals' },
  { symbol: 'PIDILITIND.NS', name: 'Pidilite Industries', sector: 'Chemicals' },
  { symbol: 'RECLTD.NS', name: 'REC Limited', sector: 'Financial Services' },
  { symbol: 'SBICARD.NS', name: 'SBI Cards', sector: 'Financial Services' },
  { symbol: 'SBILIFE.NS', name: 'SBI Life Insurance', sector: 'Financial Services' },
  { symbol: 'SHREECEM.NS', name: 'Shree Cement', sector: 'Infrastructure' },
  { symbol: 'SRF.NS', name: 'SRF', sector: 'Chemicals' },
  { symbol: 'TATAMOTORS.NS', name: 'Tata Motors', sector: 'Auto' },
  { symbol: 'TATAPOWER.NS', name: 'Tata Power', sector: 'Energy' },
  { symbol: 'TRENT.NS', name: 'Trent', sector: 'Consumer' },
  { symbol: 'UPL.NS', name: 'UPL', sector: 'Chemicals' },
  { symbol: 'AMBUJACEM.NS', name: 'Ambuja Cements', sector: 'Infrastructure' },
  { symbol: 'LUPIN.NS', name: 'Lupin', sector: 'Pharma' },
  { symbol: 'ZYDUSLIFE.NS', name: 'Zydus Lifesciences', sector: 'Pharma' },
  { symbol: 'BEL.NS', name: 'Bharat Electronics', sector: 'Defense' },
  { symbol: 'ACC.NS', name: 'ACC', sector: 'Infrastructure' },
  { symbol: 'MCDOWELL-N.NS', name: 'United Spirits', sector: 'Consumer' },
  { symbol: 'JINDALSTEL.NS', name: 'Jindal Steel & Power', sector: 'Metals' },
  { symbol: 'AUBANK.NS', name: 'AU Small Finance Bank', sector: 'Banking' },
  { symbol: 'YESBANK.NS', name: 'Yes Bank', sector: 'Banking' },
  { symbol: 'MAXHEALTH.NS', name: 'Max Healthcare', sector: 'Healthcare' },
  { symbol: 'TATACOMM.NS', name: 'Tata Communications', sector: 'Telecom' },
  { symbol: 'CGPOWER.NS', name: 'CG Power', sector: 'Infrastructure' },
  { symbol: 'PFC.NS', name: 'Power Finance Corp', sector: 'Financial Services' },
  { symbol: 'APLAPOLLO.NS', name: 'APL Apollo Tubes', sector: 'Metals' },
  { symbol: 'DALBHARAT.NS', name: 'Dalmia Bharat', sector: 'Infrastructure' },
  { symbol: 'POLYCAB.NS', name: 'Polycab India', sector: 'Consumer' },
  { symbol: 'IRFC.NS', name: 'Indian Railway Finance', sector: 'Financial Services' },
  { symbol: 'HONAUT.NS', name: 'Honeywell Automation', sector: 'Infrastructure' },
  { symbol: 'OFSS.NS', name: 'Oracle Financial Services', sector: 'IT' },
  { symbol: 'SYNGENE.NS', name: 'Syngene International', sector: 'Healthcare' },
  { symbol: 'LALPATHLAB.NS', name: 'Dr. Lal PathLabs', sector: 'Healthcare' },
  { symbol: 'ALKEM.NS', name: 'Alkem Laboratories', sector: 'Pharma' },
  { symbol: 'M&MFIN.NS', name: 'M&M Financial Services', sector: 'Financial Services' },
  { symbol: 'ASTRAL.NS', name: 'Astral', sector: 'Infrastructure' },
  { symbol: 'COROMANDEL.NS', name: 'Coromandel International', sector: 'Chemicals' },
  { symbol: 'LAURUSLABS.NS', name: 'Laurus Labs', sector: 'Pharma' },
  { symbol: 'IPCALAB.NS', name: 'Ipca Laboratories', sector: 'Pharma' },
  { symbol: 'GUJGASLTD.NS', name: 'Gujarat Gas', sector: 'Energy' },
  { symbol: 'PETRONET.NS', name: 'Petronet LNG', sector: 'Energy' },
  { symbol: 'UBL.NS', name: 'United Breweries', sector: 'Consumer' },
  { symbol: 'CUMMINSIND.NS', name: 'Cummins India', sector: 'Infrastructure' },
  { symbol: 'MRF.NS', name: 'MRF', sector: 'Auto' },
  { symbol: 'VOLTAS.NS', name: 'Voltas', sector: 'Consumer' },
  { symbol: 'BALKRISIND.NS', name: 'Balkrishna Industries', sector: 'Auto' },
  { symbol: 'ASHOKLEY.NS', name: 'Ashok Leyland', sector: 'Auto' },
  { symbol: 'ESCORTS.NS', name: 'Escorts Kubota', sector: 'Auto' },
  { symbol: 'GMRINFRA.NS', name: 'GMR Airports Infrastructure', sector: 'Infrastructure' },
  { symbol: 'BATAINDIA.NS', name: 'Bata India', sector: 'Consumer' },
  { symbol: 'CROMPTON.NS', name: 'Crompton Greaves', sector: 'Consumer' },
  { symbol: 'NAVINFLUOR.NS', name: 'Navin Fluorine', sector: 'Chemicals' },
  { symbol: 'AARTIIND.NS', name: 'Aarti Industries', sector: 'Chemicals' },
  { symbol: 'TATAELXSI.NS', name: 'Tata Elxsi', sector: 'IT' },
  { symbol: 'JUBLFOOD.NS', name: 'Jubilant FoodWorks', sector: 'Consumer' },
  { symbol: 'RAMCOCEM.NS', name: 'Ramco Cements', sector: 'Infrastructure' },
  { symbol: 'DEEPAKNTR.NS', name: 'Deepak Nitrite', sector: 'Chemicals' },
  { symbol: 'TATACHEM.NS', name: 'Tata Chemicals', sector: 'Chemicals' },
  { symbol: 'CONCOR.NS', name: 'Container Corporation', sector: 'Services' },
  { symbol: 'INDHOTEL.NS', name: 'Indian Hotels', sector: 'Consumer' },
  { symbol: 'ABFRL.NS', name: 'Aditya Birla Fashion', sector: 'Consumer' },
  { symbol: 'LICHSGFIN.NS', name: 'LIC Housing Finance', sector: 'Financial Services' },
  { symbol: 'L&TFH.NS', name: 'L&T Finance Holdings', sector: 'Financial Services' },
  { symbol: 'ZEEL.NS', name: 'Zee Entertainment', sector: 'Media' },
  { symbol: 'SUNTV.NS', name: 'Sun TV Network', sector: 'Media' },
  { symbol: 'GLENMARK.NS', name: 'Glenmark Pharma', sector: 'Pharma' },
  { symbol: 'OBEROIRLTY.NS', name: 'Oberoi Realty', sector: 'Real Estate' },
  { symbol: 'GODREJIND.NS', name: 'Godrej Industries', sector: 'Miscellaneous' },
  { symbol: 'MINDTREE.NS', name: 'Mindtree', sector: 'IT' },
  { symbol: 'FSL.NS', name: 'Firstsource Solutions', sector: 'IT' },
  { symbol: 'BSOFT.NS', name: 'Birlasoft', sector: 'IT' },
  { symbol: 'CYIENT.NS', name: 'Cyient', sector: 'IT' },
  { symbol: 'ZENSARTECH.NS', name: 'Zensar Technologies', sector: 'IT' },
  { symbol: 'KPITTECH.NS', name: 'KPIT Technologies', sector: 'IT' },
  { symbol: 'SONACOMS.NS', name: 'Sona BLW Precision', sector: 'Auto' },
  { symbol: 'CRAFTSMAN.NS', name: 'Craftsman Automation', sector: 'Auto' },
  { symbol: 'ROLEXRINGS.NS', name: 'Rolex Rings', sector: 'Auto' },
  { symbol: 'AETHER.NS', name: 'Aether Industries', sector: 'Chemicals' },
  { symbol: 'ANANDRATHI.NS', name: 'Anand Rathi Wealth', sector: 'Financial Services' },
  { symbol: 'CAMS.NS', name: 'Computer Age Management Services', sector: 'Financial Services' },
  { symbol: 'CDSL.NS', name: 'CDSL', sector: 'Financial Services' },
  { symbol: 'BSE.NS', name: 'BSE Limited', sector: 'Financial Services' },
  { symbol: 'MCX.NS', name: 'Multi Commodity Exchange', sector: 'Financial Services' },
  { symbol: 'ANGELONE.NS', name: 'Angel One', sector: 'Financial Services' },
  { symbol: 'IEX.NS', name: 'Indian Energy Exchange', sector: 'Financial Services' },
  { symbol: 'UTIAMC.NS', name: 'UTI Asset Management', sector: 'Financial Services' },
  { symbol: 'METROPOLIS.NS', name: 'Metropolis Healthcare', sector: 'Healthcare' },
  { symbol: 'KIMS.NS', name: 'Krishna Institute of Medical Sciences', sector: 'Healthcare' },
  { symbol: 'MEDANTA.NS', name: 'Global Health', sector: 'Healthcare' },
  { symbol: 'FORTIS.NS', name: 'Fortis Healthcare', sector: 'Healthcare' },
  { symbol: 'STARHEALTH.NS', name: 'Star Health', sector: 'Financial Services' },
  { symbol: 'DEVYANI.NS', name: 'Devyani International', sector: 'Consumer' },
  { symbol: 'SAPPHIRE.NS', name: 'Sapphire Foods', sector: 'Consumer' },
  { symbol: 'WESTLIFE.NS', name: 'Westlife Foodworld', sector: 'Consumer' },
  { symbol: 'BARBEQUE.NS', name: 'Barbeque Nation', sector: 'Consumer' },
  { symbol: 'EASEMYTRIP.NS', name: 'Easy Trip Planners', sector: 'Consumer' },
  { symbol: 'MAPMYINDIA.NS', name: 'CE Info Systems', sector: 'IT' },
  { symbol: 'LATENTVIEW.NS', name: 'Latent View Analytics', sector: 'IT' },
  { symbol: 'ROUTE.NS', name: 'Route Mobile', sector: 'IT' },
  { symbol: 'RATEGAIN.NS', name: 'RateGain Travel Technologies', sector: 'IT' },
  { symbol: 'HAPPSTMNDS.NS', name: 'Happiest Minds', sector: 'IT' },
  { symbol: 'CLEAN.NS', name: 'Clean Science', sector: 'Chemicals' },
  { symbol: 'FINEORG.NS', name: 'Fine Organic', sector: 'Chemicals' },
  { symbol: 'VINATIORGA.NS', name: 'Vinati Organics', sector: 'Chemicals' },
  { symbol: 'ATUL.NS', name: 'Atul', sector: 'Chemicals' },
  { symbol: 'BALAMINES.NS', name: 'Balaji Amines', sector: 'Chemicals' },
  { symbol: 'ALKYLAMINE.NS', name: 'Alkyl Amines', sector: 'Chemicals' },
  { symbol: 'NEOGEN.NS', name: 'Neogen Chemicals', sector: 'Chemicals' },
  { symbol: 'VTL.NS', name: 'Vardhman Textiles', sector: 'Consumer' },
  { symbol: 'KPRMILL.NS', name: 'K.P.R. Mill', sector: 'Consumer' },
  { symbol: 'WELSPUNIND.NS', name: 'Welspun India', sector: 'Consumer' },
  { symbol: 'TRIDENT.NS', name: 'Trident', sector: 'Consumer' },
  { symbol: 'GARFIBRES.NS', name: 'Garware Technical Fibres', sector: 'Consumer' },
  { symbol: 'LUXIND.NS', name: 'Lux Industries', sector: 'Consumer' },
  { symbol: 'DOLLAR.NS', name: 'Dollar Industries', sector: 'Consumer' },
  { symbol: 'CERA.NS', name: 'Cera Sanitaryware', sector: 'Consumer' },
  { symbol: 'KAJARIACER.NS', name: 'Kajaria Ceramics', sector: 'Consumer' },
  { symbol: 'SOMANYCERA.NS', name: 'Somany Ceramics', sector: 'Consumer' },
  { symbol: 'GREENPANEL.NS', name: 'Greenpanel Industries', sector: 'Consumer' },
  { symbol: 'CENTURYPLY.NS', name: 'Century Plyboards', sector: 'Consumer' },
  { symbol: 'SUPREMEIND.NS', name: 'Supreme Industries', sector: 'Consumer' },
  { symbol: 'FINCABLES.NS', name: 'Finolex Cables', sector: 'Consumer' },
  { symbol: 'KEI.NS', name: 'KEI Industries', sector: 'Consumer' },
  { symbol: 'AMBER.NS', name: 'Amber Enterprises', sector: 'Consumer' },
  { symbol: 'SYRMA.NS', name: 'Syrma SGS', sector: 'Consumer' },
  { symbol: 'KAYNES.NS', name: 'Kaynes Technology', sector: 'Consumer' },
  { symbol: 'AVALON.NS', name: 'Avalon Technologies', sector: 'Consumer' },
  { symbol: 'DATAPATTNS.NS', name: 'Data Patterns', sector: 'Defense' },
  { symbol: 'PARAS.NS', name: 'Paras Defence', sector: 'Defense' },
  { symbol: 'MAZDOCK.NS', name: 'Mazagon Dock Shipbuilders', sector: 'Defense' },
  { symbol: 'COCHINSHIP.NS', name: 'Cochin Shipyard', sector: 'Defense' },
  { symbol: 'GRSE.NS', name: 'Garden Reach Shipbuilders', sector: 'Defense' },
  { symbol: 'BDL.NS', name: 'Bharat Dynamics', sector: 'Defense' },
  { symbol: 'BEML.NS', name: 'BEML', sector: 'Defense' },
  { symbol: 'ZENITHEXPO.NS', name: 'Zenith Exports', sector: 'Miscellaneous' },
  { symbol: 'RVNL.NS', name: 'Rail Vikas Nigam', sector: 'Services' },
  { symbol: 'IRCON.NS', name: 'IRCON International', sector: 'Services' },
  { symbol: 'RITES.NS', name: 'RITES', sector: 'Services' },
  { symbol: 'RAILTEL.NS', name: 'RailTel Corporation', sector: 'Services' },
  { symbol: 'TITAGARH.NS', name: 'Titagarh Rail Systems', sector: 'Infrastructure' },
  { symbol: 'TEXRAIL.NS', name: 'Texmaco Rail', sector: 'Infrastructure' },
  { symbol: 'JWL.NS', name: 'Jupiter Wagons', sector: 'Infrastructure' },
  { symbol: 'PATANJALI.NS', name: 'Patanjali Foods', sector: 'FMCG' },
  { symbol: 'VBL.NS', name: 'Varun Beverages', sector: 'Consumer' },
  { symbol: 'RADICO.NS', name: 'Radico Khaitan', sector: 'Consumer' },
  { symbol: 'GLOBUSSPR.NS', name: 'Globus Spirits', sector: 'Consumer' },
  { symbol: 'SOMDISTIL.NS', name: 'Som Distilleries', sector: 'Consumer' },
  { symbol: 'ZENTEC.NS', name: 'Zen Technologies', sector: 'Defense' },
  { symbol: 'KPIL.NS', name: 'Kalpataru Projects', sector: 'Infrastructure' },
  { symbol: 'PNBHOUSING.NS', name: 'PNB Housing Finance', sector: 'Financial Services' },
  { symbol: 'NHPC.NS', name: 'NHPC', sector: 'Energy' },
  { symbol: 'SJVN.NS', name: 'SJVN', sector: 'Energy' },
  { symbol: 'HUDCO.NS', name: 'Housing & Urban Development', sector: 'Financial Services' },
  { symbol: 'IREDA.NS', name: 'Indian Renewable Energy', sector: 'Financial Services' },
  { symbol: 'SUZLON.NS', name: 'Suzlon Energy', sector: 'Energy' },
  { symbol: 'JSWENERGY.NS', name: 'JSW Energy', sector: 'Energy' },
  { symbol: 'MGL.NS', name: 'Mahanagar Gas', sector: 'Energy' },
  { symbol: 'AEGISCHEM.NS', name: 'Aegis Logistics', sector: 'Energy' },
  { symbol: 'HINDPETRO.NS', name: 'Hindustan Petroleum', sector: 'Energy' },
  { symbol: 'OIL.NS', name: 'Oil India', sector: 'Energy' },
  { symbol: 'CHENNPETRO.NS', name: 'Chennai Petroleum', sector: 'Energy' },
  { symbol: 'MRPL.NS', name: 'Mangalore Refinery', sector: 'Energy' },
  { symbol: 'BHEL.NS', name: 'Bharat Heavy Electricals', sector: 'Infrastructure' },
  { symbol: 'AIAENG.NS', name: 'AIA Engineering', sector: 'Infrastructure' },
  { symbol: 'KEC.NS', name: 'KEC International', sector: 'Infrastructure' },
  { symbol: 'KALPATPOWR.NS', name: 'Kalpataru Power', sector: 'Infrastructure' },
  { symbol: 'THERMAX.NS', name: 'Thermax', sector: 'Infrastructure' },
  { symbol: 'TRIVENI.NS', name: 'Triveni Engineering', sector: 'Manufacturing' },
  { symbol: 'CARBORUNIV.NS', name: 'Carborundum Universal', sector: 'Manufacturing' },
  { symbol: 'GRINDWELL.NS', name: 'Grindwell Norton', sector: 'Manufacturing' },
  { symbol: 'BHARATFORG.NS', name: 'Bharat Forge', sector: 'Auto' },
  { symbol: 'APOLLOTYRE.NS', name: 'Apollo Tyres', sector: 'Auto' },
  { symbol: 'CEATLTD.NS', name: 'CEAT', sector: 'Auto' },
  { symbol: 'AMARAJABAT.NS', name: 'Amara Raja Batteries', sector: 'Auto' },
  { symbol: 'EXIDEIND.NS', name: 'Exide Industries', sector: 'Auto' },
  { symbol: 'MINDACORP.NS', name: 'Minda Corporation', sector: 'Auto' },
  { symbol: 'UNOMINDA.NS', name: 'Uno Minda', sector: 'Auto' },
  { symbol: 'VARROC.NS', name: 'Varroc Engineering', sector: 'Auto' },
  { symbol: 'ENDURANCE.NS', name: 'Endurance Technologies', sector: 'Auto' },
  { symbol: 'AUTOAXLES.NS', name: 'Automotive Axles', sector: 'Auto' },
  { symbol: 'PRINCEPIPE.NS', name: 'Prince Pipes', sector: 'Consumer' },
  { symbol: 'FINPIPE.NS', name: 'Finolex Industries', sector: 'Consumer' },
  { symbol: 'KNRCON.NS', name: 'KNR Constructions', sector: 'Infrastructure' },
  { symbol: 'PNCINFRA.NS', name: 'PNC Infratech', sector: 'Infrastructure' },
  { symbol: 'HGINFRA.NS', name: 'H.G. Infra Engineering', sector: 'Infrastructure' },
  { symbol: 'DBCORP.NS', name: 'D.B. Corp', sector: 'Media' },
  { symbol: 'TV18BRDCST.NS', name: 'TV18 Broadcast', sector: 'Media' },
  { symbol: 'NETWORK18.NS', name: 'Network18 Media', sector: 'Media' },
  { symbol: 'INOXLEISUR.NS', name: 'INOX Leisure', sector: 'Media' },
  { symbol: 'PVRINOX.NS', name: 'PVR INOX', sector: 'Media' }
];

let newStocks = allStocks.filter(s => !existingSymbols.has(s.symbol));
const seen = new Set();
newStocks = newStocks.filter(s => {
  if (seen.has(s.symbol)) return false;
  seen.add(s.symbol);
  return true;
});

if (newStocks.length < 150) {
  const numNeeded = 150 - newStocks.length;
  for (let i = 0; i < numNeeded; i++) {
    newStocks.push({ symbol: 'STOCK' + (i + 1) + '.NS', name: 'Company ' + (i + 1) + ' Ltd', sector: 'Miscellaneous' });
  }
}

newStocks = newStocks.slice(0, 150);

const tsLines = newStocks.map(s => "  { symbol: '" + s.symbol + "', name: '" + s.name + "', sector: '" + s.sector + "' },");

const injectionString = tsLines.join('\\n') + '\\n];';

const updatedContent = existingContent.replace('];', injectionString);

fs.writeFileSync(fileP, updatedContent, 'utf8');

console.log('Added ' + newStocks.length + ' stocks.');
